name: 刷步数

on:
##################################################################
  workflow_dispatch:
    inputs:
      ssh:
        description: '[ssh-actions]改成[ssh],再按[Run workflow]按钮启动,则开启SSH连接配置固件'
        required: false
        default: 'ssh-actions'
      days:
        description: '清理[X]天之前的Actions空间操作记录(可改)'
        required: true
        default: '8'
      rele:
        description: '保留[X]个Releases不被删除(可改)'
        required: true
        default: '10'
##################################################################
  schedule:
    - cron: '8 1,3,6,8,13 * * 0'
  #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          
      - name: 开始
        env:
            CONFIG: ${{ secrets.CONFIG }}
        run: |
          pip3 install requests pytz
          python3 main.py
